---
sudo: required
services:
  - docker
branches:
  only:
    - master

script:
- docker build -t stunthamster/blog:latest .

after_success:
- docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker push stunthamster/blog:latest