sudo: required

services:
  - docker

before_install:
  - docker build -t stunthamster/blog:latest .
  - docker run -d -p 127.0.0.1:80 stunthamster/blog /bin/sh -c "cd /root/sinatra; bundle exec foreman start;"
  - docker ps -a
  - docker run stunthamster/blog:latest /bin/sh -c "cd /root/sinatra; bundle exec rake test"

script:
  - bundle exec rake test